#!/bin/bash

export SPARK_HOME=/Users/sid/code/spark
export PYTHONPATH=/Users/sid/.local/lib/python2.7/site-packages:/Users/sid/code/spark-deep-learning/docs/../python:/Users/sid/code/spark/python:/Users/sid/code/spark/python/lib/py4j-0.10.6-src.zip

(cd /Users/sid/code/spark-deep-learning/docs/../python && sphinx-apidoc -f -o docs sparkdl)

pushd "/Users/sid/code/spark-deep-learning/docs"
jekyll $@
popd
