name: Test
on:
  push:
    branches:
        - master
  pull_request:
  workflow_dispatch:
jobs:
  run-unit-test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sphinx==4.4.0 pyspark==3.2.1 tensorflow-cpu==2.8.0 pytest
      - name: Make docs
        run: pushd docs/ && PYTHONPATH=.. make clean html && popd
      - name: Run tests
        run: |
          python -m pytest tests/
